from PyQt5 import QtCore, QtGui, QtWidgets
import sys
class Ui_MainCalcWindow(object):
    def setup_ui(self, MainCalcWindow):
        MainCalcWindow.setObjectName("MainCalcWindow")
        MainCalcWindow.resize(505, 600)
        MainCalcWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainCalcWindow.setWindowTitle("Simple Calculator")
        self.calc_widget = QtWidgets.QWidget(MainCalcWindow)
        self.calc_widget.setObjectName("calc_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.calc_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 484, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.main_vert_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.main_vert_layout.setContentsMargins(0, 0, 0, 0)
        self.main_vert_layout.setSpacing(0)
        self.main_vert_layout.setObjectName("main_vert_layout") 
        self.lcd_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lcd_label.setMinimumSize(QtCore.QSize(0, 100))
        self.lcd_label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Tlwg Typist")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lcd_label.setFont(font)
        self.lcd_label.setFrameShape(QtWidgets.QFrame.Box)
        self.lcd_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lcd_label.setObjectName("lcd_label")
        self.main_vert_layout.addWidget(self.lcd_label)
        self.btn_grid_layout = QtWidgets.QGridLayout()
        self.btn_grid_layout.setSpacing(0)
        self.btn_grid_layout.setObjectName("btn_grid_layout")
        self.btn_four = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_four.sizePolicy().hasHeightForWidth())
        self.btn_four.setSizePolicy(sizePolicy)
        self.btn_four.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_four.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_four.setObjectName("btn_four")
        self.btn_grid_layout.addWidget(self.btn_four, 1, 0, 1, 1)
        self.btn_subtract = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_subtract.sizePolicy().hasHeightForWidth())
        self.btn_subtract.setSizePolicy(sizePolicy)
        self.btn_subtract.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_subtract.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_subtract.setDefault(False)
        self.btn_subtract.setObjectName("btn_subtract")
        self.btn_grid_layout.addWidget(self.btn_subtract, 1, 3, 1, 1)
        self.btn_multiply = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_multiply.sizePolicy().hasHeightForWidth())
        self.btn_multiply.setSizePolicy(sizePolicy)
        self.btn_multiply.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_multiply.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_multiply.setDefault(False)
        self.btn_multiply.setObjectName("btn_multiply")
        self.btn_grid_layout.addWidget(self.btn_multiply, 2, 3, 1, 1)
        self.btn_five = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_five.sizePolicy().hasHeightForWidth())
        self.btn_five.setSizePolicy(sizePolicy)
        self.btn_five.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_five.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_five.setObjectName("btn_five")
        self.btn_grid_layout.addWidget(self.btn_five, 1, 1, 1, 1)
        self.btn_nine = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_nine.sizePolicy().hasHeightForWidth())
        self.btn_nine.setSizePolicy(sizePolicy)
        self.btn_nine.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_nine.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_nine.setObjectName("btn_nine")
        self.btn_grid_layout.addWidget(self.btn_nine, 0, 2, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear.sizePolicy().hasHeightForWidth())
        self.btn_clear.setSizePolicy(sizePolicy)
        self.btn_clear.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_clear.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_clear.setDefault(False)
        self.btn_clear.setObjectName("btn_clear")
        self.btn_grid_layout.addWidget(self.btn_clear, 4, 0, 1, 1)
        self.btn_zero = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_zero.sizePolicy().hasHeightForWidth())
        self.btn_zero.setSizePolicy(sizePolicy)
        self.btn_zero.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_zero.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_zero.setObjectName("btn_zero")
        self.btn_grid_layout.addWidget(self.btn_zero, 4, 1, 1, 1)
        self.btn_three = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_three.sizePolicy().hasHeightForWidth())
        self.btn_three.setSizePolicy(sizePolicy)
        self.btn_three.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_three.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_three.setObjectName("btn_three")
        self.btn_grid_layout.addWidget(self.btn_three, 2, 2, 1, 1)
        self.btn_one = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_one.sizePolicy().hasHeightForWidth())
        self.btn_one.setSizePolicy(sizePolicy)
        self.btn_one.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_one.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_one.setObjectName("btn_one")
        self.btn_grid_layout.addWidget(self.btn_one, 2, 0, 1, 1)
        self.btn_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_add.sizePolicy().hasHeightForWidth())
        self.btn_add.setSizePolicy(sizePolicy)
        self.btn_add.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_add.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_add.setDefault(False)
        self.btn_add.setObjectName("btn_add")
        self.btn_grid_layout.addWidget(self.btn_add, 0, 3, 1, 1)
        self.btn_seven = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_seven.sizePolicy().hasHeightForWidth())
        self.btn_seven.setSizePolicy(sizePolicy)
        self.btn_seven.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_seven.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_seven.setObjectName("btn_seven")
        self.btn_grid_layout.addWidget(self.btn_seven, 0, 0, 1, 1)
        self.btn_divide = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_divide.sizePolicy().hasHeightForWidth())
        self.btn_divide.setSizePolicy(sizePolicy)
        self.btn_divide.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_divide.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_divide.setAutoDefault(False)
        self.btn_divide.setDefault(False)
        self.btn_divide.setFlat(False)
        self.btn_divide.setObjectName("btn_divide")
        self.btn_grid_layout.addWidget(self.btn_divide, 4, 3, 1, 1)
        self.btn_equals = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_equals.sizePolicy().hasHeightForWidth())
        self.btn_equals.setSizePolicy(sizePolicy)
        self.btn_equals.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_equals.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_equals.setObjectName("btn_equals")
        self.btn_grid_layout.addWidget(self.btn_equals, 4, 2, 1, 1)
        self.btn_six = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_six.sizePolicy().hasHeightForWidth())
        self.btn_six.setSizePolicy(sizePolicy)
        self.btn_six.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_six.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_six.setObjectName("btn_six")
        self.btn_grid_layout.addWidget(self.btn_six, 1, 2, 1, 1)
        self.btn_two = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_two.sizePolicy().hasHeightForWidth())
        self.btn_two.setSizePolicy(sizePolicy)
        self.btn_two.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_two.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_two.setObjectName("btn_two")
        self.btn_grid_layout.addWidget(self.btn_two, 2, 1, 1, 1)
        self.btn_eight = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_eight.sizePolicy().hasHeightForWidth())
        self.btn_eight.setSizePolicy(sizePolicy)
        self.btn_eight.setMinimumSize(QtCore.QSize(120, 100))
        self.btn_eight.setMaximumSize(QtCore.QSize(120, 80))
        self.btn_eight.setObjectName("btn_eight")
        self.btn_grid_layout.addWidget(self.btn_eight, 0, 1, 1, 1)
        self.main_vert_layout.addLayout(self.btn_grid_layout)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.main_vert_layout.addItem(spacerItem)
        MainCalcWindow.setCentralWidget(self.calc_widget)

        self.retranslate_ui(MainCalcWindow)
        QtCore.QMetaObject.connectSlotsByName(MainCalcWindow)

    def retranslate_ui(self, MainCalcWindow):
        _translate = QtCore.QCoreApplication.translate 
        self.btn_four.setText(_translate("MainCalcWindow", "4"))
        self.btn_subtract.setText(_translate("MainCalcWindow", "-"))
        self.btn_multiply.setText(_translate("MainCalcWindow", "*"))
        self.btn_five.setText(_translate("MainCalcWindow", "5"))
        self.btn_nine.setText(_translate("MainCalcWindow", "9"))
        self.btn_clear.setText(_translate("MainCalcWindow", "AC"))
        self.btn_zero.setText(_translate("MainCalcWindow", "0"))
        self.btn_three.setText(_translate("MainCalcWindow", "3"))
        self.btn_one.setText(_translate("MainCalcWindow", "1"))
        self.btn_add.setText(_translate("MainCalcWindow", "+"))
        self.btn_seven.setText(_translate("MainCalcWindow", "7"))
        self.btn_divide.setText(_translate("MainCalcWindow", "/"))
        self.btn_equals.setText(_translate("MainCalcWindow", "="))
        self.btn_six.setText(_translate("MainCalcWindow", "6"))
        self.btn_two.setText(_translate("MainCalcWindow", "2"))
        self.btn_eight.setText(_translate("MainCalcWindow", "8"))

